-- CORVO seed principal.
--
-- Para cargar la data de la hoja sin confundirte:
--
-- 1. Asegurate de haber aplicado las migraciones, especialmente:
--    supabase/migrations/202606050001_budget_pockets.sql
--    supabase/migrations/202606050002_salary_cycle.sql
--
-- 2. Ejecuta:
--    supabase/clear_user_data.sql
--
-- 3. Ejecuta despues:
--    supabase/seed_corvo_data.sql
--
-- En ambos archivos debes reemplazar el UUID de ejemplo por el id real del usuario.
--
-- Este archivo queda solo como nota para evitar ejecutar un seed viejo por error.
